### ISSUE TITLE
CKA certification exam

### ISSUE THREAD

**Issue by vikasgubbi** [JeepGuy/k8s#1]
Sincere request  to add CKA  sample exam scenarios to the github or  pointers to it.

**Comment by JeepGuy** [comment]
Good idea. I will add that to the README.md file tonight (I am at work and cannot do it now)... 

Do you have a different suggestion, Please advise, thank you.

:)

**Comment by JeepGuy** [comment]
https://www.cncf.io/certification/expert/

**Comment by vikasgubbi** [comment]
exam scenarios questions if you include it would be great help
